# Generated by Django 6.1.1 on 2026-10-01 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paid', 'Paid')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='inventory.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='reservation_status_0064e5_idx'), models.Index(fields=['user', 'status'], name='reservation_user_id_cbd2d6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_hold_per_user')],
            },
        ),
    ]
