# Generated by Django 6.1.1 on 2026-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='limited-edition-sneaker', max_length=100, unique=True)),
                ('total_stock', models.PositiveIntegerField(default=20)),
                ('available_stock', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('available_stock__gte', 0)), name='inventory_available_stock_non_negative'), models.CheckConstraint(condition=models.Q(('total_stock__gte', models.F('available_stock'))), name='inventory_available_stock_not_above_total')],
            },
        ),
    ]
