# Generated by Django 6.1.1 on 2026-10-01 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='reservation.hold')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='inventory.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['inventory', 'status', 'created_at', 'id'], name='waitlist_wa_invento_ab6246_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('user',), name='one_waiting_entry_per_user')],
            },
        ),
    ]
