# Generated by Django 6.1.1 on 2026-10-01 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('processed', 'Processed'), ('duplicate', 'Duplicate'), ('late', 'Late'), ('ignored', 'Ignored')], max_length=20, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='reservation.hold')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_id'], name='payment_pay_payment_06e806_idx'), models.Index(fields=['hold', 'received_at'], name='payment_pay_hold_id_764563_idx')],
            },
        ),
    ]
